language: php

php:
  - 5.5
  - 5.6

mysql:
  database: travis_ci_optimizedb_test
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Install Drush
  - composer global require drush/drush:dev-master
  - phpenv rehash

before_script:
  - git clone git://github.com/youngj/httpserver.git
  - mv httpserver /home/travis/.composer/vendor/drush/drush/lib

  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database travis_ci_optimizedb_test'
  - drush --yes core-quick-drupal --core=drupal-8 --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/travis_ci_optimizedb_test --enable=simpletest travis_ci_optimizedb_test

  # reference and enable travis_ci_drupal_module_example in build site
  - ln -s $(readlink -e $(cd -)) travis_ci_optimizedb_test/drupal-8/modules/optimizedb
  - cd travis_ci_optimizedb_test/drupal-8

  - drush st
  - drush --yes en optimizedb

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: /usr/bin/php ./core/scripts/run-tests.sh --php /usr/bin/php --url http://127.0.0.1:8080 --module optimizedb
